cassandra:
  cluster:
    - "cassandra"
  keyspace: "tatanka"

gdax:
  api_key: "your_gdax_api_key"
  api_secret: "your_gdax_api_secret"
  api_passphrase: "your_gdax_api_passphrase"

strategies:
  - name: macd
    options:
      long: 26
      short: 12

  - name: rsi
    options:
      overbought_rsi: 85
      oversold_rsi: 30
